#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cinder
Version  : 8.0.0
Release  : 32
URL      : http://tarballs.openstack.org/cinder/cinder-8.0.0.tar.gz
Source0  : http://tarballs.openstack.org/cinder/cinder-8.0.0.tar.gz
Source1  : cinder.tmpfiles
Summary  : OpenStack Block Storage
Group    : Development/Tools
License  : Apache-2.0
Requires: cinder-bin
Requires: cinder-python3
Requires: cinder-config
Requires: cinder-data
Requires: cinder-license
Requires: cinder-python
Requires: Babel
Requires: Paste
Requires: PasteDeploy
Requires: Routes
Requires: SQLAlchemy
Requires: WebOb
Requires: decorator
Requires: enum34
Requires: eventlet
Requires: google-api-python-client
Requires: greenlet
Requires: httplib2
Requires: iso8601
Requires: keystonemiddleware
Requires: lxml
Requires: oauth2client
Requires: os-brick
Requires: os-win
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.context
Requires: oslo.db
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.messaging
Requires: oslo.middleware
Requires: oslo.policy
Requires: oslo.reports
Requires: oslo.rootwrap
Requires: oslo.serialization
Requires: oslo.service
Requires: oslo.utils
Requires: oslo.versionedobjects
Requires: oslo.vmware
Requires: osprofiler
Requires: paramiko
Requires: pbr
Requires: pycrypto
Requires: pyparsing
Requires: python-barbicanclient
Requires: python-glanceclient
Requires: python-keystoneclient
Requires: python-novaclient
Requires: python-swiftclient
Requires: pytz
Requires: requests
Requires: retrying
Requires: rtslib-fb
Requires: simplejson
Requires: six
Requires: sqlalchemy-migrate
Requires: stevedore
Requires: suds-jurko
Requires: taskflow
Requires: tooz
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: 0001-default-config.patch
Patch2: 0002-cinder-sudoers-entry.patch
Patch3: 0003-Add-cinder-s-tgt-config.patch
Patch4: 0004-move-rootwrap-location.patch
Patch5: 0006-Set-default-syslog.patch

%description
CINDER
        ======
        
        You have come across a storage service for an open cloud computing service.
        It has identified itself as `Cinder`. It was abstracted from the Nova project.

%package bin
Summary: bin components for the cinder package.
Group: Binaries
Requires: cinder-data
Requires: cinder-config
Requires: cinder-license

%description bin
bin components for the cinder package.


%package config
Summary: config components for the cinder package.
Group: Default

%description config
config components for the cinder package.


%package data
Summary: data components for the cinder package.
Group: Data

%description data
data components for the cinder package.


%package license
Summary: license components for the cinder package.
Group: Default

%description license
license components for the cinder package.


%package python
Summary: python components for the cinder package.
Group: Default
Requires: cinder-python3

%description python
python components for the cinder package.


%package python3
Summary: python3 components for the cinder package.
Group: Default
Requires: python3-core

%description python3
python3 components for the cinder package.


%prep
%setup -q -n cinder-8.0.0
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532217096
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/cinder
cp LICENSE %{buildroot}/usr/share/doc/cinder/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/tmpfiles.d/cinder.conf
## make_install_append content
install -d -m 755 %{buildroot}/usr/share/defaults/cinder
install -p -D -m 644 etc/cinder/*.conf %{buildroot}/usr/share/defaults/cinder/
install -p -D -m 644 etc/cinder/*.ini %{buildroot}/usr/share/defaults/cinder/
install -p -D -m 644 etc/cinder/*.json %{buildroot}/usr/share/defaults/cinder/
install -p -D -m 644 etc/cinder/cinder.conf.sample %{buildroot}/usr/share/defaults/cinder/cinder.conf
install -d -m 755 %{buildroot}/usr/share/cinder/rootwrap.d
mv %{buildroot}/usr/share/defaults/cinder/rootwrap.conf %{buildroot}/usr/share/cinder/
install -p -D -m 640 etc/cinder/rootwrap.d/*.filters %{buildroot}/usr/share/cinder/rootwrap.d/
install -d -m 750 %{buildroot}/usr/share/defaults/sudo/sudoers.d
install -p -D -m 440 etc/sudoers.d/cinder.sudoers %{buildroot}/usr/share/defaults/sudo/sudoers.d/cinder
install -d -m 750 %{buildroot}/usr/share/defaults/tgt/conf.d/
install -p -D -m 640 cinder.tgt %{buildroot}/usr/share/defaults/tgt/conf.d/cinder.conf
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cinder-all
/usr/bin/cinder-api
/usr/bin/cinder-backup
/usr/bin/cinder-manage
/usr/bin/cinder-rootwrap
/usr/bin/cinder-rtstool
/usr/bin/cinder-scheduler
/usr/bin/cinder-volume
/usr/bin/cinder-volume-usage-audit
/usr/bin/cinder-wsgi

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/cinder.conf

%files data
%defattr(-,root,root,-)
/usr/share/cinder/rootwrap.conf
/usr/share/cinder/rootwrap.d/volume.filters
/usr/share/defaults/cinder/api-httpd.conf
/usr/share/defaults/cinder/api-paste.ini
/usr/share/defaults/cinder/cinder.conf
/usr/share/defaults/cinder/logging_sample.conf
/usr/share/defaults/cinder/policy.json
/usr/share/defaults/sudo/sudoers.d/cinder
/usr/share/defaults/tgt/conf.d/cinder.conf

%files license
%defattr(-,root,root,-)
/usr/share/doc/cinder/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
